### ISSUE TITLE
New GamerOS Version

### ISSUE THREAD

**Issue by ABO896** [ChrisTitusTech/ntlite-configs#2]
Today a new version of GamerOS has been released. Here is the URL so you can update it:
https://www.ntlite.com/community/index.php?threads/gameros-windows-10-11-diy-preset.2350/page-15#post-29772

**Comment by ChrisTitusTech** [comment]
Thanks, I'll get this merged soon.

**Comment by ChrisTitusTech** [comment]
Merged in 6a017e75219a0730cc5d0b77070a0beefab3538a
