### ISSUE TITLE
Final script preset.

### ISSUE THREAD

**Issue by github59173** [ChrisTitusTech/ntlite-configs#3]
Missing post setup script error when using gaming final preset.

**Comment by SaiSaaketh** [comment]
Yes Me having same problems

**Comment by Vorshim92** [comment]
just add it in the post setup settings. https://www.ntlite.com/community/index.php?attachments/gameros-10-final-zip.8478/

p.s. hi @ChrisTitusTech ! sorry for spam, did you forget the .ps1 file intentionally?

**Comment by mignochrono** [comment]
i think maybe he did? or maybe its not supposed to be uploaded to GitHub? idk if its against the TOS or something. you can find the file in the forums. the latest one i could find was  [https://www.ntlite.com/community/index.php?attachments/gameros-10-final-zip.9036/]. but im not really sure where the file is supposed to be placed
